config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :poptarts
end

app/models/poptart.rb
class Poptart < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/poptarts_controller.rb
class PoptartsController < ApplicationController

  def index
    @poptart = Poptart.new
    @poptarts = Poptart.all
  end

  def create
    @poptart = Poptart.create(poptart_params)
    if @poptart.save
      redirect_to poptarts_path
    else
      render :index
    end
  end

  def show
    @poptart = Poptart.find(params[:id])
  end

  def edit
    @poptart = Poptart.find(params[:id])
  end

  def update
    @poptart = Poptart.find(params[:id])
    @poptart.update_attributes!(poptart_params)

    redirect_to poptarts_path
  end

  def destroy
    @poptart = Poptart.find(params[:id]).delete

    redirect_to poptarts_path
  end

  private
  def poptart_params
    params.require(:poptart).permit(:flavor, :topping)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrudPoptarts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/poptarts/edit.html.erb
<%= form_for @poptart do |f| %>
  <p>
    <%= f.label :flavor %>
    <%= f.text_field :flavor %>
  </p>
  <p>
    <%= f.label :topping %>
    <%= f.text_field :topping %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

app/views/poptarts/index.html.erb
<%= form_for @poptart do |f| %>
  <p>
    <%= f.label :flavor %>
    <%= f.text_field :flavor %>
  </p>
  <p>
    <%= f.label :topping %>
    <%= f.text_field :topping %>
  </p>
  <p>
    <%= f.submit 'Create Poptarts' %>
  </p>
<% end %>

<% @poptarts.each do |poptart| %>
  <ul>
    <li>
      <%= link_to poptart.flavor, poptart_path(poptart) %>
      <br>
      <%= poptart.topping %>
    </li>
  </ul>
<% end %>

app/views/poptarts/show.html.erb
<ul>
  <li>
    <%= @poptart.flavor %>
    <br>
    <%= @poptart.topping %>
  </li>
</ul>

<%= link_to 'Edit', edit_poptart_path(@poptart) %>
<%= link_to 'Delete', poptart_path(@poptart), method: :delete %>

app/views/welcome/index.html.erb
<h2>Welcome</h2>

<%= link_to 'Add Poptarts', poptarts_path %>